name: finance_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.5.0
  
  # Otros
  intl: ^0.18.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Configuraci√≥n de Flutter
flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/google_logo.png